In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.array([ [1,2,3,4],
                 [5,6,7,np.nan],
                 [9,10,np.nan, 11],
                 [12,13,np.nan, np.nan]
    
])

df = pd.DataFrame(data,columns=["A","B","C","D"])

df

      A     B    C     D
0   1.0   2.0  3.0   4.0
1   5.0   6.0  7.0   NaN
2   9.0  10.0  NaN  11.0
3  12.0  13.0  NaN   NaN

In [3]:
df.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2  False  False   True  False
3  False  False   True   True

In [4]:
df.isnull().sum()

A    0
B    0
C    2
D    2
dtype: int64

In [5]:
df.dropna(axis=0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [6]:
df

      A     B    C     D
0   1.0   2.0  3.0   4.0
1   5.0   6.0  7.0   NaN
2   9.0  10.0  NaN  11.0
3  12.0  13.0  NaN   NaN

In [7]:
df.dropna(axis=1)

      A     B
0   1.0   2.0
1   5.0   6.0
2   9.0  10.0
3  12.0  13.0

In [8]:
df.dropna(how = "all")

      A     B    C     D
0   1.0   2.0  3.0   4.0
1   5.0   6.0  7.0   NaN
2   9.0  10.0  NaN  11.0
3  12.0  13.0  NaN   NaN

In [9]:
df

      A     B    C     D
0   1.0   2.0  3.0   4.0
1   5.0   6.0  7.0   NaN
2   9.0  10.0  NaN  11.0
3  12.0  13.0  NaN   NaN

In [10]:
df.dropna(thresh = 3)

     A     B    C     D
0  1.0   2.0  3.0   4.0
1  5.0   6.0  7.0   NaN
2  9.0  10.0  NaN  11.0

In [11]:
df.dropna(thresh = 0)

      A     B    C     D
0   1.0   2.0  3.0   4.0
1   5.0   6.0  7.0   NaN
2   9.0  10.0  NaN  11.0
3  12.0  13.0  NaN   NaN

In [12]:
df.dropna(thresh = 1)

      A     B    C     D
0   1.0   2.0  3.0   4.0
1   5.0   6.0  7.0   NaN
2   9.0  10.0  NaN  11.0
3  12.0  13.0  NaN   NaN

In [17]:
df.dropna(thresh = 3)

     A     B    C     D
0  1.0   2.0  3.0   4.0
1  5.0   6.0  7.0   NaN
2  9.0  10.0  NaN  11.0

In [20]:
df.dropna(subset= ["C", "D"])

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [21]:
from sklearn.impute import SimpleImputer

In [22]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy="mean")

In [23]:
imp_mean = imp_mean.fit(df.values)

In [24]:
imputed_data = imp_mean.transform(df.values)

In [25]:
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7. ,  7.5],
       [ 9. , 10. ,  5. , 11. ],
       [12. , 13. ,  5. ,  7.5]])

In [27]:
df.fillna(df.())

      A     B    C     D
0   1.0   2.0  3.0   4.0
1   5.0   6.0  7.0   7.5
2   9.0  10.0  5.0  11.0
3  12.0  13.0  5.0   7.5