In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([
    ["red", "L", 5.0, "class1"],
    ["blue", "XL", 2.0, "class2"],
    ["black", "M", 3.0, "class1"]
])

df

       0   1    2       3
0    red   L  5.0  class1
1   blue  XL  2.0  class2
2  black   M  3.0  class1

In [3]:
df.columns = ["color", "size", "age", "classlabel"]

df

   color size  age classlabel
0    red    L  5.0     class1
1   blue   XL  2.0     class2
2  black    M  3.0     class1

In [6]:
df.dtypes

color          object
size           object
age           float64
classlabel     object
dtype: object

In [7]:
size_mapping = {"XL": 3, "L":2, "M":1}
df["size"] = df["size"].map(size_mapping)
df

   color  size  age classlabel
0    red     2  5.0     class1
1   blue     3  2.0     class2
2  black     1  3.0     class1

In [9]:
class_mapping = {label: idx for idx,label in enumerate(np.unique(df["classlabel"]))}
class_mapping

{'class1': 0, 'class2': 1}

In [10]:
df["classlabel"] = df["classlabel"].map(class_mapping)
df

   color  size  age  classlabel
0    red     2  5.0           0
1   blue     3  2.0           1
2  black     1  3.0           0

In [14]:
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df["color"].values)
y

array([2, 1, 0])

In [15]:
X = df[["color", "size", "age"]].values
color_le = LabelEncoder()
X[:, 0 ] = color_le.fit_transform(X[: , 0])
X

array([[2, 2, 5.0],
       [1, 3, 2.0],
       [0, 1, 3.0]], dtype=object)

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
color_ohe = OneHotEncoder()

In [18]:
X[:,0]

array([2, 1, 0], dtype=object)

In [19]:
X[:,0].reshape(-1,1)

array([[2],
       [1],
       [0]], dtype=object)

In [20]:
color_ohe.fit_transform(X[:,0].reshape(-1,1)).toarray()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [21]:
from sklearn.compose import ColumnTransformer

In [22]:
c_transf = ColumnTransformer([
    ("onehot", OneHotEncoder(), [0]),
    ("nothing", "passthrough", [1,2])
])

X

array([[2, 2, 5.0],
       [1, 3, 2.0],
       [0, 1, 3.0]], dtype=object)

In [23]:
c_transf.fit_transform(X).astype(float)

array([[0., 0., 1., 2., 5.],
       [0., 1., 0., 3., 2.],
       [1., 0., 0., 1., 3.]])

In [24]:
pd.get_dummies(df[["color", "size", "age"]])

   size  age  color_black  color_blue  color_red
0     2  5.0            0           0          1
1     3  2.0            0           1          0
2     1  3.0            1           0          0

In [25]:
pd.get_dummies(df[["color", "size", "age"]], drop_first = True)

   size  age  color_blue  color_red
0     2  5.0           0          1
1     3  2.0           1          0
2     1  3.0           0          0

In [26]:
color_ohe=OneHotEncoder(categories="auto", drop="first")

c_transf = ColumnTransformer([
    ("onehot", color_ohe, [0]),
    ("nothing", "passthrough", [1,2])
])

c_transf.fit_transform(X).astype(float)

array([[0., 1., 2., 5.],
       [1., 0., 3., 2.],
       [0., 0., 1., 3.]])